# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TS4wm9ek-Hu7Je0n2XRDqR1ZFNDVlVe6
"""

import math
number = float(input("Enter a number: "))
square_root = math.sqrt(number)
log_value = math.log(number)
sine_value = math.sin(number)

print("Square root is ",square_root)
print("Natural log (ln) is ",log_value)
print("Sine of radians is",sine_value)