# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tJFduvhOkimRR8Y1JCQEhMOcxDncN2sc
"""

def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        result = 1
        for i in range(2, n + 1):
            result *= i
        return result
number = int(input("Enter a number to calculate its factorial: "))
print("The factorial is:",factorial(number))